Github pagesへのデプロイを行うワークフローを追加
future-architect/uroborosql-fmt pull request #5
Opened 2023-09-19 09:16 UTC by abcd-ts

2023-09-19 09:44 UTC, tanzaku commented on wasm/main.js
> +      convert_double_colon_cast: false,
::をCASTに変換できるというのをデモで見せられるようにtrueに変更お願いします

2023-09-19 10:54 UTC, ota-meshi requested changes
wasm/uroborosql-fmt.jsとwasm/uroborosql-fmt.wasmはGitHubActionsで生成されるものではありませんか？
その場合.gitignoreに追加することができると思います。ご確認お願いします。

2023-09-22 06:23 UTC, abcd-ts commented
> wasm/uroborosql-fmt.jsとwasm/uroborosql-fmt.wasmはGitHubActionsで生成されるものではありませんか？ その場合.gitignoreに追加することができると思います。ご確認お願いします。

ありがとうございます。`source build.sh` で生成されたファイルをそのまま置いていましたが、確かに不要なので .gitignore に追加しました。

2023-09-22 07:24 UTC, ota-meshi requested changes

2023-09-22 07:24 UTC, ota-meshi commented on .github/workflows/build-wasm.yml
> +  push:
ここはmainブランチのみをターゲットにした方が良いです。
このままでは関係ないブランチをpushしたタイミングでそのブランチを使用して、ビルドされサイトが公開されてしまいます。

一時的にmain以外のブランチからビルドしてサイトを公開したい場合は、`workflow_dispatch: null`を設定することで（すでに設定されています）手動で、行うことができるようになります。（このブランチでは現在使用できませんがおそらくmainにマージした後でできるようになるのではないかと思います。）

<img width="1081" alt="image" src="https://github.com/future-architect/uroborosql-fmt/assets/16508807/4bea8dc4-beec-475d-b8e6-6bf8126b2a12">

2023-09-22 07:30 UTC, ota-meshi approved these changes
Looks good to me!

2023-09-22 07:32 UTC, abcd-ts commented on .github/workflows/build-wasm.yml
> +  push:
> 一時的にmain以外のブランチからビルドしてサイトを公開したい場合は、workflow_dispatch: nullを設定することで（すでに設定されています）手動で、行うことができるようになります。（このリポジトリでは現在使用できませんがおそらくmainにマージした後でできるようになるのではないかと思います。）

ありがとうございます。
まさにそれを意図して追加しましたが、デフォルトブランチに反映させないと使用できないようですね。

main ブランチのみに修正しました。

2023-09-22 07:39 UTC, merged